language: ruby
cache: bundler
rvm:
  - 2.1.2

env:
#  - DB=sqlite
#  - DB=mysql
  - DB=postgresql

deploy:
  provider: heroku
  api_key:
    secure: 334d93d0-a30a-4df0-b183-c529c0b4caad
  app: arcane-lake-66240
  strategy: git
  run:
    - "rake db:migrate"
#script:
#  - rake